export const FACILITY_PREMIUM_FREQUENCY_ID = {
  UNDEFINED: 0,
  MONTHLY: 1,
  QUARTERLY: 2,
  SEMI_ANNUALLY: 3,
  ANNUALLY: 4,
};

export const FACILITY_PREMIUM_TYPE_ID = {
  UNDEFINED: 0,
  IN_ADVANCE: 1,
  IN_ARREARS: 2,
  AT_MATURITY: 3,
};
