export const FEE_TYPE = {
  ADVANCE: 'In advance',
  ARREAR: 'In arrear',
  MATURITY: 'At maturity',
};

export const FACILITY_FEE_TYPE_GEF = {
  IN_ARREARS_MONTHLY: 'IN_ARREARS_MONTHLY',
  IN_ARREARS_QUARTLY: 'IN_ARREARS_QUARTLY',
  IN_ARREARS_SEMI_ANNUALLY: 'IN_ARREARS_SEMI_ANNUALLY',
  IN_ARREARS_ANNUALLY: 'IN_ARREARS_ANNUALLY',
  IN_ADVANCE_QUARTERLY: 'IN_ADVANCE_QUARTERLY',
  IN_ADVANCE_MONTHLY: 'IN_ADVANCE_MONTHLY',
  IN_ADVANCE_SEMI_ANNUALLY: 'IN_ADVANCE_SEMI_ANNUALLY',
  IN_ADVANCE_ANNUALLY: 'IN_ADVANCE_ANNUALLY',
  AT_MATURITY: 'AT_MATURITY',
};
